### ISSUE TITLE
Implement mapping an enumeration to a dropdown

### ISSUE THREAD

**Issue by dominikag2** [Kentico/xperience-by-kentico-quickstart-guides#35]
Create a universal way of mapping an Enum type to dropdown options control, e.g., to be used for a widget property.

Explore the existing mapper in the Product comparator widget and identify if it needs to be refactored in any way to achieve the above.

**Comment by seangwright** [comment]
The Community Portal uses a [DropDownOptionsProvider](https://github.com/Kentico/community-portal/blob/v28.2.1.7/src/Kentico.Community.Portal.Web/Components/EnumDropDownOptionsProvider.cs), driven by enums, that provides a nice API when used [with widget properties](https://github.com/Kentico/community-portal/blob/v28.2.1.7/src/Kentico.Community.Portal.Web/Components/Widgets/LinkList/LinkListWidget.cs#L81).

*Enum*

```csharp
public enum LinkListDesign
{
    [Description("Link list")]
    Link_List,
    [Description("Call to actions")]
    Call_To_Actions,
    [Description("List in Card")]
    List_In_Card,
}
```

*Widget property*

```csharp
    [DropDownComponent(
        Label = "Design",
        ExplanationText = "Component layout and design",
        DataProviderType = typeof(EnumDropDownOptionsProvider<LinkListDesign>),
        Order = 3
    )]
    public string DesignSource { get; set; } = nameof(LinkListDesign.Link_List);
    public LinkListDesign DesignParsed => EnumDropDownOptionsProvider<LinkListDesign>.Parse(DesignSource, LinkListDesign.Link_List);
}
```

This is great when you want semantic options for presentation, but don't want to use strings or store the design implementation (like CSS classes) in the database.

**Comment by dominikag2** [comment]
Thank you, @seangwright that's exactly our plan - using the Community portal as inspiration :)
